"""Remove white background from icon and generate all Tauri icon sizes."""
from PIL import Image, ImageFilter
import os

src = os.path.join(os.path.dirname(__file__), "..", "icon.png")
out_dir = os.path.join(os.path.dirname(__file__), "..", "src-tauri", "icons")
os.makedirs(out_dir, exist_ok=True)

img = Image.open(src).convert("RGBA")
pixels = img.load()
w, h = img.size

# Remove white/near-white background by flood-filling from corners
# Use a threshold approach: pixels close to white become transparent
from collections import deque

visited = set()
queue = deque()

# Seed from edges
for x in range(w):
    queue.append((x, 0))
    queue.append((x, h - 1))
for y in range(h):
    queue.append((0, y))
    queue.append((w - 1, y))

threshold = 230  # pixels with R,G,B all above this are "white-ish"

while queue:
    x, y = queue.popleft()
    if (x, y) in visited or x < 0 or x >= w or y < 0 or y >= h:
        continue
    visited.add((x, y))
    r, g, b, a = pixels[x, y]
    if r > threshold and g > threshold and b > threshold:
        pixels[x, y] = (r, g, b, 0)  # make transparent
        for dx, dy in [(-1,0),(1,0),(0,-1),(0,1)]:
            nx, ny = x+dx, y+dy
            if (nx, ny) not in visited:
                queue.append((nx, ny))

# Also handle the slight off-white edges with anti-aliasing
# Make semi-transparent pixels at the boundary smoother
for x in range(w):
    for y in range(h):
        r, g, b, a = pixels[x, y]
        if a > 0 and r > 210 and g > 210 and b > 210:
            # Check if near a transparent pixel
            neighbors_transparent = 0
            for dx, dy in [(-1,0),(1,0),(0,-1),(0,1)]:
                nx, ny = x+dx, y+dy
                if 0 <= nx < w and 0 <= ny < h:
                    _, _, _, na = pixels[nx, ny]
                    if na == 0:
                        neighbors_transparent += 1
            if neighbors_transparent > 0:
                # Fade based on how white it is
                whiteness = min(r, g, b) / 255.0
                new_alpha = int(a * (1 - (whiteness - 0.82) / 0.18))
                new_alpha = max(0, min(255, new_alpha))
                pixels[x, y] = (r, g, b, new_alpha)

# Save the transparent version
transparent = img.copy()

# Tauri icon sizes needed
# https://tauri.app/v2/guides/features/icons/
sizes = {
    "32x32.png": 32,
    "128x128.png": 128,
    "128x128@2x.png": 256,
    "icon.png": 512,  # general purpose
}

for name, size in sizes.items():
    resized = transparent.resize((size, size), Image.LANCZOS)
    resized.save(os.path.join(out_dir, name))
    print(f"  Saved {name} ({size}x{size})")

# Generate .ico (Windows) with multiple sizes
ico_sizes = [(16,16), (24,24), (32,32), (48,48), (64,64), (128,128), (256,256)]
ico_images = []
for s in ico_sizes:
    ico_images.append(transparent.resize(s, Image.LANCZOS))
ico_images[0].save(os.path.join(out_dir, "icon.ico"), format="ICO", sizes=ico_sizes, append_images=ico_images[1:])
print("  Saved icon.ico (multi-size)")

# Generate .icns placeholder (macOS) — save as 512x512 PNG, cargo tauri icon can convert
# For now just ensure we have the PNGs, icns can be generated by tauri build
icon512 = transparent.resize((512, 512), Image.LANCZOS)
icon512.save(os.path.join(out_dir, "Square512x512Logo.png"))
print("  Saved Square512x512Logo.png")

# Also save 1024 for high-res
icon1024 = transparent.resize((1024, 1024), Image.LANCZOS)
icon1024.save(os.path.join(out_dir, "Square1024x1024Logo.png"))

# StoreLogo
icon50 = transparent.resize((50, 50), Image.LANCZOS)
icon50.save(os.path.join(out_dir, "StoreLogo.png"))
print("  Saved StoreLogo.png")

# Save transparent source for site favicon too
icon192 = transparent.resize((192, 192), Image.LANCZOS)
icon192.save(os.path.join(os.path.dirname(__file__), "favicon.png"))
print("  Saved site/favicon.png")

print("\nDone! All icons generated.")
